### ISSUE TITLE
You should be able to specify which hooks go to which channels

### ISSUE THREAD

**Issue by nyuszika7h** [notifico/notifico#118] opened 2015-02-26 19:11 UTC
Right now, you can't add a hook that only goes to one of the channels without creating a new project, and adding that channel and the hook there.

**Comment by TkTech** [comment] 2015-02-26 20:44
Closing as a duplicate of #65

**Closed by TkTech** 2015-02-26 20:44 UTC

**Comment by nyuszika7h** [comment] 2015-03-01 13:48
Oh, didn't know there's an issue for this. I guess I should use the search feature more. :P

**Comment by TkTech** [comment] 2015-03-01 19:58
It's an old one :) The current rough rewrite no longer has projects and is just a hook -> channel.
